[services]
lutris = True
gog = True
egs = True
ea_app = True
ubisoft = True
steam = True

[lutris]
width = 800
height = 600
maximized = True
selected_category = category:all
view_type = grid

[list view]
название_column_width = 200
год_column_width = 60
раннер_column_width = 120
платформа_column_width = 120
последнийзапуск_column_width = 120
времявигре_column_width = 100
датаустановки_column_width = 120

