name: Sync Fork

on:
  schedule:
    - cron: '*/30 * * * *' # every 30 minutes
  workflow_dispatch: # on button click

jobs:
  sync:

    runs-on: ubuntu-latest

    steps:
      - name: Sync fork
        uses: tgymnich/fork-sync@v2.0.10
        with:
          token: ${{ secrets.TOKEN }}
          base: dev-next
          head: dev-next
      - uses: actions/checkout@v5
        with:
          token: ${{ secrets.TOKEN }}
          path: 'singbox'
          fetch-depth: 0
      - name:
        run: | 
          cd $GITHUB_WORKSPACE/singbox
          go mod vendor
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add -A
          git commit -m "Automated changes"
          git push
